In [5]:
import numpy as np


In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print(arr.data)

In [12]:
print(arr.ndim)
print(arr.shape)
print(type(arr))

2
(2, 4)
<class 'numpy.ndarray'>


# Statiscial Funtion

In [16]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [17]:
a.dtype

dtype('int32')

In [21]:
a.itemsize


4

In [22]:
a.size

12

In [24]:
a.shape

(3, 4)

In [29]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=np.float64)
print(a,"\n")
print(a.dtype)
print(a.itemsize)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

float64
8


In [32]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=np.complex64)
print(a,"\n")
print(a.dtype)
print(a.itemsize)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j  8.+0.j]
 [ 9.+0.j 10.+0.j 11.+0.j 12.+0.j]] 

complex64
8


In [33]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=np.complex128)
print(a,"\n")
print(a.dtype)
print(a.itemsize)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j  8.+0.j]
 [ 9.+0.j 10.+0.j 11.+0.j 12.+0.j]] 

complex128
16


In [34]:
print(np.sum(a))

(78+0j)


In [36]:
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))


[15.+0.j 18.+0.j 21.+0.j 24.+0.j]
[10.+0.j 26.+0.j 42.+0.j]


In [39]:
print(np.amin(a))
print(np.amin(a,axis=0))
print(np.amin(a,axis=1))

(1+0j)
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
[1.+0.j 5.+0.j 9.+0.j]


In [43]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.amax(a))
print(np.amax(a,axis=0))
print(np.amax(a,axis=1))

12
[ 9 10 11 12]
[ 4  8 12]


In [49]:
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))
print(np.std(a))
print(np.std(a,axis=0))
print(np.std(a,axis=1))

6.5
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]
6.5
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]
3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]


In [51]:
print(np.var(a))
print(np.var(a,axis=0))
print(np.var(a,axis=1))

11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]


In [53]:
#weighted average
print(np.average(a))

6.5


In [54]:
c=np.array([1,2,3, 4,5,6])
print(c)

[1 2 3 4 5 6]


In [55]:
weight=np.array([0.25,0.56,0.36,0.45,0.12,0.10])
print(weight)

[0.25 0.56 0.36 0.45 0.12 0.1 ]


In [56]:
print(np.average(c,weights=weight))

2.9619565217391304


In [61]:
#peak to peak
print(np.ptp(c))
print(np.ptp(a))
print(np.ptp(a,1))

5
11
[3 3 3]


In [67]:
#reshape
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,"\n")
print(np.size(a))
print(a.shape)
print(a.reshape(4,3))
print(np.size(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

12
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
12


In [79]:
#slicing
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,"\n")
print(a[1,3])
print(a[2,2])
print(a[0,2])
print(a[1,0:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

8
11
3
[5 6]


In [85]:
#stacking
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,"\n")
b = np.array([[13,14,15,16],[17,18,19,20],[21,22,23,24]])
print(b,"\n")
print(np.hstack((a,b)),"\n")
print(np.hstack((b,a)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]] 

[[13 14 15 16  1  2  3  4]
 [17 18 19 20  5  6  7  8]
 [21 22 23 24  9 10 11 12]]


In [87]:
print(np.vstack((a,b)),"\n")
print(np.vstack((b,a)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [99]:
#generating random numbers#
from numpy import random
a=random.randint(100)
print(a)

88
